name: SellShip
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.5.5+58
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  app_review: ^2.0.1
  adobe_xd: ^1.0.0+1
  alphabet_list_scroll_view: ^1.0.6
  badges: ^1.1.1
  cached_network_image: ^2.3.2+1
  carousel_slider: ^2.2.1
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^6.0.0
  firebase_core : ^0.5.0
  firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  flag: ^3.0.5
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.1.2
  flutter_credit_card: ^0.1.3
  flutter_easyrefresh: ^2.1.5
  flutter_email_sender: ^3.0.1
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_native_admob: ^2.1.0+3
  flutter_signin_button: ^1.1.0
  flutter_slidable: ^0.5.7
  flutter_spinkit: "^4.1.2"
  flutter_sticky_header: "^0.4.2"
  flutter_staggered_grid_view:
    git:
      url: https://github.com/BertrandBev/flutter_staggered_grid_view.git
  flutter_secure_storage: ^3.3.4
  font_awesome_flutter: ^8.8.1
  geocoder: ^0.2.1
  geolocator: ^6.0.0+4
  giffy_dialog: ^1.8.0
  google_maps_flutter: ^0.5.32
  http: ^0.12.2
  image_picker: ^0.6.7+7
  intercom_flutter: ^2.2.0+1
  intl: ^0.16.1
  intl_phone_number_input: ^0.5.1
  jiffy: ^3.0.1
  locally: ^0.2.6+9
  location: ^3.0.2
  multi_image_picker: ^4.7.14
  path_provider: ^1.6.14
  package_info: ^0.4.3
  photo_view: ^0.10.2
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  random_string: ^2.1.0
  search_map_place: ^0.3.0
  share: ^0.6.5
  shimmer: ^1.1.1
  shared_preferences: ^0.5.10
  sign_in_with_apple: ^2.5.2
  simple_animations: ^2.2.2
  stripe_payment: ^1.0.7
  stripe_sdk: ^3.0.1+1
  smooth_star_rating: ^1.1.1
  timeago: ^2.0.27
  url_launcher: ^5.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - yay.gif
    - sss.jpg
    - little_theologians_4x.png
    - logo.png
    - onboard1.png
    - onboard2.png
    - messages.png
    - items.png
    - favourites.png
    - oops.gif
    - personplaceholder.png
    - fashion.png
    - laptop.png
    - sports.png
    - home.jpg
    - Books.jpeg
    - laptops.jpeg
    - phones.jpeg
    - 143.png
    - logotransparent.png
    - assets/electronics/
    - assets/beauty/
    - assets/fashion/
    - assets/home/
    - assets/motor/
    - assets/sport/
    - assets/books/
    - assets/baby/
    - assets/property/
    - assets/homeshow/
    - uaeflag.png
    - usaflag.png
    - assets/women/
    - assets/men/
    - assets/boys/
    - assets/girls/
    - assets/category/
    - verified.png
    - assets/secure.png
    - assets/043.png
    - assets/051.png
    - assets/062.png
    - assets/153.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Helvetica
     fonts:
       - asset: assets/fonts/ProximaNova-Regular.otf


#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
