name: SellShip
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.24+24
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  app_review: ^2.0.1
  app_settings: 4.0.3
  alphabet_list_scroll_view: ^1.0.6
  badges: ^1.1.1
  flutter_svg: 0.18.0
  cached_network_image: ^2.3.2+1
  cupertino_icons: ^0.1.3
  dio: ^3.0.10
  dotted_border: 1.0.6
  percent_indicator: ^2.1.9
  firebase_analytics: ^6.2.0
  firebase_auth: ^0.18.4+1
  firebase_auth_oauth: ^0.2.3
  flag: ^3.0.5
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.1.2
  flutter_credit_card: ^0.1.3
  flutter_easyrefresh: ^2.1.5
  flutter_facebook_login: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_signin_button: ^1.1.0
  flutter_slidable: ^0.5.7
  flutter_spinkit: "^4.1.2"
  flutter_staggered_grid_view: ^0.3.4
  flutter_secure_storage: ^3.3.4
  font_awesome_flutter: ^8.8.1
  geocoding: 1.0.4+1
  geolocator: ^6.0.0+4
  giffy_dialog: ^1.8.0
  google_maps_flutter: ^0.5.32
  http: ^0.12.2
  image_picker: ^0.6.7+7
  intercom_flutter: ^2.2.0+1
  intl: ^0.16.1
  intl_phone_number_input: ^0.5.1
  jiffy: ^3.0.1
  locally: ^0.2.6+9
  location: ^3.0.2
  multi_image_picker: ^4.7.14
  numeral: 1.0.4
  path_provider: ^1.6.14
  package_info: ^0.4.3
  permission_handler: 5.0.1+1
  progress_dialog: ^1.2.4
  provider: ^4.3.2+2
  random_string: ^2.1.0
  search_map_place: ^0.3.0
  substring_highlight: ^0.1.2
  flutter_material_color_picker: ^1.0.5
  share: ^0.6.5
  shimmer: ^1.1.1
  apple_sign_in: ^0.1.0
  shared_preferences: ^0.5.10
  simple_animations: ^2.2.2
  smooth_star_rating: ^1.1.1
  timeago: ^2.0.27
  url_launcher: ^5.6.0
  auth_buttons: 0.0.4
  email_validator: 1.0.6
  onesignal_flutter: ^2.6.1
  flutter_inappwebview: ^4.0.0+4
  dropdown_search: ^0.4.8
  flutter_branch_sdk: ^1.3.0
  carousel_slider: ^3.0.0
  json_serializable: ^3.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - yay.gif
    - sss.jpg
    - little_theologians_4x.png
    - logo.png
    - onboard1.png
    - onboard2.png
    - messages.png
    - items.png
    - favourites.png
    - oops.gif
    - personplaceholder.png
    - fashion.png
    - laptop.png
    - sports.png
    - home.jpg
    - Books.jpeg
    - assets/165.png
    - laptops.jpeg
    - phones.jpeg
    - 143.png
    - assets/184.png
    - assets/021.png
    - assets/support.png
    - assets/support.svg
    - logotransparent.png
    - assets/bottomnavbar/
    - uaeflag.png
    - usaflag.png
    - assets/logonew.png
    - assets/photoguidelines/
    - verified.png
    - assets/secure.png
    - assets/043.png
    - assets/051.png
    - assets/062.png
    - assets/153.png
    - assets/024.png
    - assets/bgonboard.png
    - assets/LoginBG.png
    - assets/LoginBG.svg
    - assets/interests/
    - assets/storename.jpg
    - assets/storedetails.jpg
    - assets/celebration.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 900


#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
