name: SellShip
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.10+60
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  in_app_review: ^2.0.2
  alphabet_list_scroll_view: ^2.0.0
  badges: ^2.0.0-nullsafety.1
  flutter_svg: ^0.21.0+1
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  dotted_border: ^2.0.0
  percent_indicator: ^3.0.1
  firebase_analytics: ^8.0.3
  firebase_auth: ^1.1.3
  firebase_auth_oauth: ^1.0.1
  flag: ^5.0.0-nullsafety
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.2.0
  flutter_credit_card: ^2.0.0
  flutter_easyrefresh: ^2.2.1
  font_awesome_flutter: ^9.0.0
  flutter_slidable: ^0.6.0
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_secure_storage: ^4.2.0
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  google_maps_flutter: ^2.0.3
  http: ^0.13.3
  image_picker: ^0.7.4
  intercom_flutter: ^3.2.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  jiffy: ^4.1.0
  locally: ^1.0.5
  location: ^4.1.1
  multi_image_picker: ^4.8.00
  slugid: ^1.1.0
  grouped_list: ^4.0.0
  flutter_feather_icons: ^2.0.0+1
  flutter_login_facebook: ^1.0.1
  path_provider: ^2.0.1
  package_info: ^2.0.0
  permission_handler: ^7.1.0
  provider: ^5.0.0
  random_string: ^2.2.0-nullsafety
  substring_highlight: ^1.0.26
  share: ^2.0.1
  shimmer: ^2.0.0
  shared_preferences: ^2.0.5
  simple_animations: ^3.1.1
  timeago: ^3.0.2
  url_launcher: ^6.0.3
  auth_buttons: ^1.0.1
  email_validator: ^2.0.1
  onesignal_flutter: ^3.0.0-beta3
  flutter_inappwebview: ^5.3.2
  dropdown_search: ^0.6.1
  flutter_branch_sdk: ^3.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  json_serializable: ^4.1.1
  flutter_image_compress: ^1.0.0
  sentry_flutter: ^5.0.0
  flutter_rating_bar: ^4.0.0
  flutter_html: ^2.0.0-nullsafety.0
  stripe_payment: ^1.1.0
  stripe_sdk: ^5.0.0-nullsafety.0
  video_player: ^2.1.1
  introduction_screen: ^2.1.0
  google_sign_in: ^5.0.2




dev_dependencies:
  flutter_test:
    sdk: flutter





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - yay.gif
    - sss.jpg
    - little_theologians_4x.png
    - logo.png
    - onboard1.png
    - onboard2.png
    - messages.png
    - items.png
    - favourites.png
    - oops.gif
    - personplaceholder.png
    - fashion.png
    - laptop.png
    - sports.png
    - home.jpg
    - Books.jpeg
    - assets/165.png
    - laptops.jpeg
    - phones.jpeg
    - 143.png
    - assets/184.png
    - assets/021.png
    - assets/support.png
    - assets/support.svg
    - logotransparent.png
    - assets/bottomnavbar/
    - uaeflag.png
    - usaflag.png
    - assets/logonew.png
    - assets/photoguidelines/
    - verified.png
    - assets/secure.png
    - assets/043.png
    - assets/051.png
    - assets/062.png
    - assets/153.png
    - assets/024.png
    - assets/bgonboard.png
    - assets/LoginBG.png
    - assets/LoginBG.svg
    - assets/interests/
    - assets/storename.jpg
    - assets/storedetails.jpg
    - assets/celebration.png
    - assets/error404.png
    - assets/chatbg.png
    - assets/onboardingvideo.MOV
    - assets/onboarding/
    - assets/PRELOVED.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Gilroy-Regular.otf
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 900


#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
