export 'package:SellShip/screens/OTPScreen.dart';
export 'package:SellShip/screens/ReviewBuyer.dart';
export 'package:SellShip/screens/ReviewSeller.dart';
export 'package:SellShip/screens/addbrans.dart';
export 'package:SellShip/screens/addcategory.dart';
export 'package:SellShip/screens/additem.dart';
export 'package:SellShip/screens/addpayment.dart';
export 'package:SellShip/screens/address.dart';
export 'package:SellShip/screens/addsubcategory.dart';
export 'package:SellShip/screens/addsubsubcategory.dart';
export 'package:SellShip/screens/balance.dart';

export 'package:SellShip/screens/categorydetail.dart';
export 'package:SellShip/screens/changecountry.dart';
export 'package:SellShip/screens/chatpageview.dart';
export 'package:SellShip/screens/checkout.dart';
export 'package:SellShip/screens/checkoutuae.dart';
export 'package:SellShip/screens/comments.dart';
export 'package:SellShip/screens/details.dart';
export 'package:SellShip/screens/edititem.dart';
export 'package:SellShip/screens/editprofile.dart';
export 'package:SellShip/screens/favourites.dart';
export 'package:SellShip/screens/featureitem.dart';
export 'package:SellShip/screens/forgotpassword.dart';

export 'package:SellShip/screens/home.dart';
export 'package:SellShip/screens/loginPage.dart';
export 'package:SellShip/screens/messages.dart';
export 'package:SellShip/screens/myitems.dart';
export 'package:SellShip/screens/notifications.dart';
export 'package:SellShip/screens/onboarding.dart';
export 'package:SellShip/screens/orderbuyer.dart';
export 'package:SellShip/screens/orderbuyeruae.dart';
export 'package:SellShip/screens/orders.dart';
export 'package:SellShip/screens/orderseller.dart';
export 'package:SellShip/screens/orderselleruae.dart';
export 'package:SellShip/screens/otpinput.dart';
export 'package:SellShip/screens/paymentdone.dart';
export 'package:SellShip/screens/privacypolicy.dart';
export 'package:SellShip/screens/profile.dart';
export 'package:SellShip/screens/reviews.dart';
export 'package:SellShip/screens/rootscreen.dart';
export 'package:SellShip/screens/search.dart';
export 'package:SellShip/screens/settings.dart';
export 'package:SellShip/screens/signUpPage.dart';
export 'package:SellShip/screens/starterscreen.dart';

export 'package:SellShip/screens/termscondition.dart';
export 'package:SellShip/screens/test.dart';
export 'package:SellShip/screens/useritems.dart';

class Routes {
  static final String addBrands = '/addBrands';
  static final String addCategory = '/addCategory';
  static final String addItem = '/addItem';
  static final String addPayment = '/addPayment';
  static final String address = '/address';
  static final String addSubCategory = '/addSubCategory';
  static final String addSubSubCategory = '/addSubSubCategory';
  static final String balance = '/balance';
  static final String boysFashion = '/boysFashion';
  static final String categories = '/categories';
  static final String categoryDetail = '/categoryDetail';
  static final String changeCountry = '/changeCountry';
  static final String chatPageView = '/chatPageView';
  static final String checkout = '/checkout';
  static final String checkoutUAE = '/checkoutUAE';
  static final String comments = '/comments';
  static final String details = '/details';
  static final String editItem = '/editItem';
  static final String editProfile = '/editProfile';
  static final String favourites = '/favourites';
  static final String featureItem = '/featureItem';
  static final String forgotPassword = '/forgotPassword';
  static final String girlsFashion = '/girlsFashion';
  static final String home = '/home';
  static final String loginPage = '/loginPage';
  static final String loginProfile = '/loginProfile';
  static final String menFashion = '/menFashion';
  static final String messages = '/messages';
  static final String myItems = '/myItems';
  static final String nearMe = '/nearMe';
  static final String notifications = '/notifications';
  static final String onBoarding = '/onBoarding';
  static final String orderBuyer = '/orderBuyer';
  static final String orderBuyerUAE = '/orderBuyerUAE';
  static final String orders = '/orders';
  static final String orderSeller = '/orderSeller';
  static final String orderSellerUAE = '/orderSellerUAE';
  static final String otpInput = '/otpInput';
  static final String otpScreen = '/otpScreen';
  static final String paymentDone = '/paymentDone';
  static final String privacyPolicy = '/privacyPolicy';
  static final String profile = '/profile';
  static final String recentlyAdded = '/recentlyAdded';
  static final String reviewBuyer = '/reviewBuyer';
  static final String reviews = '/reviews';
  static final String reviewSeller = '/reviewSeller';
  static final String rootScreen = '/rootScreen';
  static final String search = '/search';
  static final String settings = '/settings';
  static final String signUpPage = '/signUpPage';
  static final String signUpProfile = '/signUpProfile';
  static final String starterScreen = '/starterScreen';
  static final String subCategory = '/subCategory';
  static final String termsAndConditions = '/termsAndConditions';
  static final String test = '/test';
  static final String userItems = '/userItems';
  static final String womenFashion = '/womenFashion';
}
