import 'package:flutter/material.dart';

class PrivacyPolicy extends StatelessWidget {
  final String pdfText = """PRIVACY POLICY

Welcome to SellShip! 

SellShip is owned and operated by RentHet Inc.

SellShip values your privacy. This notice describes what information we collect, how we use it, and, if necessary, those with whom we share it. 

By downloading and using the SellShip application and website, you are accepting the practices described in this Privacy Policy. Your use of the application and website is also subject to our Terms and Conditions.

This Privacy Policy may change from time to time. Your continued use of the application and website after we make changes is deemed to be acceptance of those changes, so please check the policy periodically for updates. This Privacy Policy has been developed and is maintained in accordance with all applicable federal and international laws and regulations.


GENERAL INFORMATION
The personal data of the users that are collected and processed through:
SellShip App (Android and iOS version – Available on Google Play and App store)
Play store - https://play.google.com/store/apps/details?id=com.zad.sellship&hl=en
App store - https://apps.apple.com/us/app/sellship-local-classifieds/id1506496966?ls=1
Will be under responsibility and in charge of:
RentHet Inc.
supportship@sellship.co

(Hereinafter referred to as “SellShip”). 

TYPES OF INFORMATION GATHERED
The information we learn from customers helps personalize and continually improve your experience at SellShip. Here are the types of information we gather:
Information You Give Us. You provide information when you download the app, search, read and watch the content, use the services or communicate with us. As a result of those actions, you might supply us with the following information:
•	First and last name
•	Email address
•	Country/province/state
•	Phone number (includes WhatsApp)
•	Payment information
•	IP address
•	Any additional information relating to you that you provide to us directly through our websites or indirectly through our websites or online presence such as ‘cookies’.
SellShip will not collect any personally identifiable information about you, unless you provide it.
Payment information: Your payment information will be treated and safeguarded with total security and with the exclusive purpose of processing payment for the products. SellShip reserves the right to contract any payment platform available in the market, which treats your data for the exclusive purpose of processing payment for the products.
GOOGLE Analytics. We use Google Analytics provided by Google, Inc., USA (“Google”). These tool and technologies collect and analyze certain types of information, including IP addresses, device and software identifiers, referring and exit URLs, feature use metrics and statistics, usage and purchase history, media access control address (MAC Address), mobile unique device identifiers, and other similar information via the use of cookies. The information generated by Google Analytics (including your IP address) may be transmitted to and stored by Google on servers in the United States. We use the GOOGLE Analytics collection of data to enhance the website and platform and improve our service.
Please consult Google's privacy policy here:
https://policies.google.com/privacy
Automatic Information. Like many websites, we use "cookies." We obtain certain types of anonymous information which is not personally identifiable when your web browser accesses SellShip or third-party content served by or on behalf of SellShip on other websites. Some of the information we collect and analyze includes the Internet protocol (IP) address; computer and connection information such as browser type, version, and connection speed; purchase history; and the content you searched for, viewed, and possibly purchased.

HOW LONG WE KEEP YOUR DATA
Personal data will be kept for the time necessary for the provision of the services or as long as the user does not close his account or withdraw his consent. The user's personal data will be deleted from our database immediately the user's account is closed or his consent withdrawn.

HOW WE USE YOUR INFORMATION. 
In general, we use the information we collect primarily to provide, maintain, protect and improve our current application, website and services. We use personal information collected through our site as described below and described elsewhere in this Policy to:
•	Identify you as a user in our system.
•	Provide the application (Available on Google Play and App store).
•	User registration.
•	Publish user content (Photos of the goods).
•	Provide the services (Publication of goods of registered users).
•	Provide chat service between users.
•	Improve our services, website, and how we operate our business.
•	Understand and enhance your experience using our website and services.
•	Send emails through bulk email delivery platforms such as MailChimp and Klaviyo.
•	Respond to your comments or questions through our support team (Chat and email).
•	Send you related information, including confirmations, invoices, technical notices, updates, security alerts and support and administrative messages.
•	Communicate with you about upcoming events and news about services offered by SellShip and our selected partners.
•	Marketing purposes of SellShip.
•	Link or combine your information with other information we get from third parties to help understand your needs and provide you with better service.
•	Protect, investigate and deter against fraudulent, unauthorized or illegal activity.

HOW DO YOU GET MY CONSENT?
By downloading the application, registering, using the services and providing us with personal information to communicate with you, you agree that we collect and use your information. You can withdraw your consent, contact us through the contact information or the contact page.

HOW WE SHARE INFORMATION
Information about our customers is an important part of our business, and we are not in the business of selling it to others. We share customer information only as described below.
Third-Party Service Providers. We employ other companies and individuals to perform functions on our behalf. Examples include process payments, sending email, analyzing data, providing marketing assistance, providing search results and links. They have access to personal information needed to perform their functions, but may not use it for other purposes.
Business Transfers. In the event that SellShip creates, merges with, or is acquired by another entity, your information will most likely be transferred. SellShip will email you or place a prominent notice on our Website before your information becomes subject to another privacy policy.
Protection of SellShip and others. We release personal information when we believe release is appropriate to comply with the law, enforce or apply our Terms and conditions and other agreements, or protect the rights, property, or safety of SellShip, our users or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction.
With Your Consent. Other than as set out above, you will receive notice when personally identifiable information about you might go to third parties, and you will have an opportunity to choose not to share the information.
Anonymous Information. SellShip uses the anonymous browsing information collected automatically by our servers primarily to help us administer and improve the platform and website. We may also use aggregated anonymous information to provide information about the website to potential business partners and other unaffiliated entities. This information is not personally identifiable.
Email Address. The email address that you supply to us for purposes of receiving our email communications will never be rented or sold to a third party.

PROTECTING YOUR INFORMATION
We work to protect the security of your information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you input. If transactions are processed on the Website, transaction information is transmitted to and from the Website in encrypted form using industry-standard SSL connections to help protect such information from interception. We restrict authorized access to your personal information to those persons who have a legitimate purpose to know that information to provide products or services to you and those persons you have authorized to have access to such information.
SellShip follows generally accepted industry standards to protect the personal information submitted to us, both during transmission and once SellShip receives it. No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while SellShip strives to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security. 
We will not sell, distribute, or lease your personal information to third parties unless we have your permission or are required by law to do so.

YOUR RIGHTS
You have the following rights in relation to your personal data provided to SellShip:
•	Access your personal data.
•	Request the correction of inaccurate data.
•	Request its deletion.
•	Request limitation of the processing of your data.
•	Oppose the treatment of your data.
•	Request your portability.
•	Not be subject to automated individual decisions.
The Users can exercise all these rights contacting us through the contact information or the contact page and indicating the reason for his request.
Without preconception to any other administrative appeal or legal action, the User shall have the right to submit a claim to a Control Authority, in particular in the Member State in which he or she has their habitual residence, place of work or place of the alleged infringement. If you consider that the processing of your personal data is not appropriate to the regulations, as well as in the case of not seeing the exercise of your rights satisfied. The control authority in which the claim was filed will inform the claimant about the course and result of the claim.

CALIFORNIA ONLINE PRIVACY PROTECTION ACT COMPLIANCE (CalOPPA)
CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require any person or company in the United States (and conceivably the world) that operates websites collecting Personally Identifiable Information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals or companies with whom it is being shared.
Because we value your privacy, we have taken the necessary precautions to be in compliance with the California Online Privacy Protection Act (CalOPPA). 
According to the California Online Privacy act, you have the following rights:
•	Know what personal data is being collected.
•	Know whether your personal data is sold or disclosed and to whom.
•	Access to your personal data.
•	Request to delete any personal information about you.
•	Not be discriminated against for exercising their privacy rights.

CHILDREN’S ONLINE PRIVACY PROTECTION 
We are in compliance with the requirements of the California Online Privacy Protection Act (CalOPPA) regarding the protection of the personal data of minors. We do not collect any information from anyone under 13 years of age. Our website, platform and services are all directed to people who are at least 18 years old or older.

EDITING AND DELETING INFORMATION
If you believe that any information, we are holding on you is incorrect or incomplete, please write to or email us as soon as possible. We will promptly correct any information found to be incorrect. You can change, modify, rectify and delete your Information at any time, please contact us through the contact information.
To opt-out of SellShip email, follow the instructions included in the email. Your request should be processed within 48 hours.

SUPPLIERS AND OTHER THIRD PARTIES
Except as otherwise expressly included in this Privacy Policy, this document addresses only the use and disclosure of information SellShip collects from you. If you disclose your information to others, whether other users or suppliers on SellShip, different rules may apply to their use or disclosure of the information you disclose to them. SellShip does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. SellShip is not responsible for the privacy or security practices of other websites on the Internet, even those linked to or from the SellShip site. SellShip encourages you to ask questions before you disclose your personal information to others.

CHANGES TO THIS PRIVACY POLICY
SellShip will post modifications by date to this Privacy Policy to inform you of any changes. SellShip reserves the right to modify this Privacy Policy at any time, please review it frequently.

ENFORCEMENT
SellShip regularly reviews its compliance with this Policy. Please feel free to direct any questions or concerns regarding this Policy or SellShip treatment of personal information by contacting us.
When we receive formal written complaints, it is SellShip policy to contact the complaining user regarding his or her concerns. We will cooperate with the appropriate regulatory authorities, including local data protection authorities, to resolve any complaints regarding the transfer of personal data that cannot be resolved between SellShip and an individual.

CONTACT US
If you have questions or concerns about these Privacy Policy and the handling and security of your data on this site, please contact us throw our contact page or contact at:
supportship@sellship.co



""";

  Widget build(BuildContext context) {
    return SafeArea(
        child: new Scaffold(
            appBar: new AppBar(
              backgroundColor: Colors.deepOrange,
              title: const Text(
                'Privacy Policy',
                style: TextStyle(color: Colors.white),
              ),
              leading: InkWell(
                onTap: () {
                  Navigator.of(context).pop();
                },
                child: Icon(
                  Icons.arrow_back_ios,
                  color: Colors.white,
                ),
              ),
            ),
            backgroundColor: Colors.white,
            body: SingleChildScrollView(
              child: Padding(
                padding: const EdgeInsets.all(8.0),
                child: Text(pdfText),
              ),
            )));
  }
}
